name: Gherkin Tests
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.7.12' # Replace with the Flutter version you are using
      - name: Install dependencies
        working-directory: ./app
        run: flutter pub get
      - name: Install Ninja
        run: sudo apt-get install ninja-build
      - name: Set up environment variables
        env:
          CMAKE_MAKE_PROGRAM: ninja
          CMAKE_CXX_COMPILER: g++
        run: |
          echo "CMAKE_MAKE_PROGRAM=${CMAKE_MAKE_PROGRAM}" >> $GITHUB_ENV
          echo "CMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER}" >> $GITHUB_ENV
      - name: Run Gherkin tests
        working-directory: ./app
        run: flutter drive --target=test_driver/app.dart --driver=test_driver/test_config.dart -d linux
