name: Gherkin Tests
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
      - name: Run Gherkin tests
        run:  |
          cd app
          flutter drive --target=test_driver/app.dart --driver=test_driver/app_test.dart
          
