name: Gherkin Tests
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.7.12' # Replace with the Flutter version you are using
      - name: Install dependencies
        working-directory: ./app
        run: flutter pub get
      - name: Install Ninja
        run: sudo apt-get install ninja-build
      - name: Set CMAKE_MAKE_PROGRAM
        run: echo "::set-env name=CMAKE_MAKE_PROGRAM::ninja"
      - name: Set CMAKE_CXX_COMPILER
        run: echo "::set-env name=CMAKE_CXX_COMPILER::g++"
      - name: Run Gherkin tests
        working-directory: ./app
        run: flutter drive --target=test_driver/app.dart --driver=test_driver/test_config.dart -d linux
